# Generated by Django 6.0.7 on 2026-07-27 06:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminAttendanceSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('college_name', models.CharField(max_length=150)),
                ('attendance_pct', models.DecimalField(decimal_places=1, default=0, max_digits=5)),
                ('present_count', models.PositiveIntegerField(default=0)),
                ('absent_count', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['-attendance_pct'],
            },
        ),
        migrations.CreateModel(
            name='AdminInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_no', models.CharField(max_length=30)),
                ('college_name', models.CharField(max_length=150)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('issued_date', models.DateField()),
                ('status', models.CharField(choices=[('paid', 'Paid'), ('due', 'Due'), ('overdue', 'Overdue')], default='due', max_length=20)),
            ],
            options={
                'ordering': ['-issued_date'],
            },
        ),
        migrations.CreateModel(
            name='AdminProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('college_name', models.CharField(max_length=150)),
                ('budget', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('spent', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('status', models.CharField(choices=[('In Progress', 'In Progress'), ('On Hold', 'On Hold'), ('Completed', 'Completed')], default='In Progress', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='AdminScheduleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('assessment', 'Assessment'), ('interview', 'Interview')], max_length=20)),
                ('title', models.CharField(max_length=150)),
                ('college_name', models.CharField(max_length=150)),
                ('date', models.DateField()),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='AdminStudentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('college_name', models.CharField(max_length=150)),
                ('department', models.CharField(max_length=20)),
                ('performance_pct', models.DecimalField(decimal_places=1, default=0, max_digits=5)),
                ('status', models.CharField(default='Active', max_length=20)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('body', models.CharField(max_length=300)),
                ('audience', models.CharField(default='All Colleges', max_length=60)),
                ('posted_date', models.DateField()),
            ],
            options={
                'ordering': ['-posted_date'],
            },
        ),
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('total_students', models.PositiveIntegerField(default=0)),
                ('present_count', models.PositiveIntegerField(default=0)),
                ('absent_count', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='PartnerCollege',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('students_count', models.PositiveIntegerField(default=0)),
                ('active_programs', models.PositiveIntegerField(default=0)),
                ('pending_payment', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('status', models.CharField(choices=[('active', 'Active'), ('payment_due', 'Payment Due')], default='active', max_length=20)),
            ],
            options={
                'ordering': ['-students_count'],
            },
        ),
        migrations.CreateModel(
            name='SupportTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_code', models.CharField(max_length=20)),
                ('college_name', models.CharField(max_length=150)),
                ('issue', models.CharField(max_length=200)),
                ('priority', models.CharField(choices=[('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], default='Medium', max_length=20)),
                ('status', models.CharField(choices=[('Open', 'Open'), ('In Progress', 'In Progress'), ('Resolved', 'Resolved')], default='Open', max_length=20)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='SyllabusUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program', models.CharField(max_length=150)),
                ('course', models.CharField(max_length=150)),
                ('college_name', models.CharField(max_length=150)),
                ('updated_date', models.DateField()),
                ('updated_by', models.CharField(max_length=120)),
            ],
            options={
                'ordering': ['-updated_date'],
            },
        ),
        migrations.CreateModel(
            name='TopProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('students_count', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['-students_count'],
            },
        ),
        migrations.CreateModel(
            name='AdminProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active_trainings', models.PositiveIntegerField(default=0)),
                ('assessments_conducted', models.PositiveIntegerField(default=0)),
                ('open_issues', models.PositiveIntegerField(default=0)),
                ('colleges_onboarded_this_month', models.PositiveIntegerField(default=0)),
                ('students_enrolled_this_month', models.PositiveIntegerField(default=0)),
                ('assessments_taken_this_month', models.PositiveIntegerField(default=0)),
                ('placements_this_month', models.PositiveIntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='admin_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BatchAttendanceEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('present', models.PositiveIntegerField(default=0)),
                ('absent', models.PositiveIntegerField(default=0)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_entries', to='portal.batch')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='CollegeProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('college_name', models.CharField(default='ABC Engineering College', max_length=150)),
                ('location', models.CharField(default='Bengaluru, Karnataka', max_length=150)),
                ('academic_year', models.CharField(default='2024 - 2025', max_length=20)),
                ('semester_label', models.CharField(default='Even Semester', max_length=40)),
                ('placement_eligible', models.PositiveIntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='college_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CollegeNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=250)),
                ('posted_date', models.DateField()),
                ('is_read', models.BooleanField(default=False)),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='portal.collegeprofile')),
            ],
            options={
                'ordering': ['-posted_date'],
            },
        ),
        migrations.CreateModel(
            name='CollegeAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('department', models.CharField(max_length=20)),
                ('date', models.DateField()),
                ('avg_score', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('status', models.CharField(choices=[('completed', 'Completed'), ('scheduled', 'Scheduled')], default='completed', max_length=20)),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='portal.collegeprofile')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='CollegeProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('students_count', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed')], default='active', max_length=20)),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programs', to='portal.collegeprofile')),
            ],
        ),
        migrations.CreateModel(
            name='CollegeQuickReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quick_reports', to='portal.collegeprofile')),
            ],
        ),
        migrations.CreateModel(
            name='CollegeStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('department', models.CharField(max_length=20)),
                ('avg_score', models.DecimalField(decimal_places=1, default=0, max_digits=5)),
                ('attendance_pct', models.DecimalField(decimal_places=1, default=0, max_digits=5)),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='portal.collegeprofile')),
            ],
            options={
                'ordering': ['-avg_score'],
            },
        ),
        migrations.CreateModel(
            name='CollegeTrendPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month_label', models.CharField(max_length=20)),
                ('order', models.PositiveIntegerField(default=0)),
                ('avg_percentage', models.DecimalField(decimal_places=1, default=0, max_digits=5)),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trend_points', to='portal.collegeprofile')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='CompanyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(default='TechSolutions Pvt. Ltd.', max_length=150)),
                ('total_drives', models.PositiveIntegerField(default=0)),
                ('hired', models.PositiveIntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='company_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CompanyInterview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate_name', models.CharField(max_length=120)),
                ('interview_type', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('time', models.TimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='scheduled', max_length=20)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interviews', to='portal.companyprofile')),
            ],
            options={
                'ordering': ['date', 'time'],
            },
        ),
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('department', models.CharField(max_length=20)),
                ('aptitude_score', models.PositiveIntegerField(default=0)),
                ('technical_score', models.PositiveIntegerField(default=0)),
                ('communication_score', models.PositiveIntegerField(default=0)),
                ('shortlist_status', models.CharField(choices=[('shortlisted', 'Shortlisted'), ('under_review', 'Under Review'), ('not_selected', 'Not Selected')], default='under_review', max_length=20)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidates', to='portal.companyprofile')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=150)),
                ('total_students', models.PositiveIntegerField(default=0)),
                ('avg_performance', models.DecimalField(decimal_places=1, default=0, max_digits=5)),
                ('attendance_pct', models.DecimalField(decimal_places=1, default=0, max_digits=5)),
                ('assessments_taken', models.PositiveIntegerField(default=0)),
                ('training_hours', models.PositiveIntegerField(default=0)),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='portal.collegeprofile')),
            ],
            options={
                'ordering': ['-total_students'],
            },
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('department', models.CharField(max_length=20)),
                ('rating', models.DecimalField(decimal_places=1, default=0, max_digits=3)),
                ('classes_taken', models.PositiveIntegerField(default=0)),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faculty', to='portal.collegeprofile')),
            ],
            options={
                'ordering': ['-rating'],
            },
        ),
        migrations.CreateModel(
            name='JobDrive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('location', models.CharField(max_length=120)),
                ('date', models.DateField()),
                ('positions', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('upcoming', 'Upcoming'), ('ongoing', 'Ongoing'), ('completed', 'Completed')], default='upcoming', max_length=20)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_drives', to='portal.companyprofile')),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate_name', models.CharField(max_length=120)),
                ('position', models.CharField(max_length=120)),
                ('package_lpa', models.DecimalField(decimal_places=1, default=0, max_digits=6)),
                ('status', models.CharField(choices=[('offered', 'Offered'), ('accepted', 'Accepted'), ('declined', 'Declined')], default='offered', max_length=20)),
                ('offer_date', models.DateField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='portal.companyprofile')),
            ],
            options={
                'ordering': ['-offer_date'],
            },
        ),
        migrations.CreateModel(
            name='PlacementRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=150)),
                ('students_placed', models.PositiveIntegerField(default=0)),
                ('package_lpa', models.DecimalField(decimal_places=1, default=0, max_digits=6)),
                ('drive_date', models.DateField()),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='placements', to='portal.collegeprofile')),
            ],
            options={
                'ordering': ['-drive_date'],
            },
        ),
        migrations.CreateModel(
            name='SyllabusCoverage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=150)),
                ('department', models.CharField(max_length=20)),
                ('coverage_pct', models.PositiveIntegerField(default=0)),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='syllabus_coverage', to='portal.collegeprofile')),
            ],
            options={
                'ordering': ['-coverage_pct'],
            },
        ),
        migrations.CreateModel(
            name='TrainerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assessments_created', models.PositiveIntegerField(default=0)),
                ('assignments_uploaded', models.PositiveIntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='trainer_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TrainerCalendarEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('batch_name', models.CharField(max_length=150)),
                ('date', models.DateField()),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendar_events', to='portal.trainerprofile')),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='TrainerAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('batch_name', models.CharField(max_length=150)),
                ('due_date', models.DateField()),
                ('submissions_count', models.PositiveIntegerField(default=0)),
                ('total_students', models.PositiveIntegerField(default=0)),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='portal.trainerprofile')),
            ],
            options={
                'ordering': ['due_date'],
            },
        ),
        migrations.CreateModel(
            name='TrainerAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('avg_score', models.DecimalField(decimal_places=1, default=0, max_digits=5)),
                ('date', models.DateField()),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='portal.trainerprofile')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='QuestionBankItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=120)),
                ('topic', models.CharField(max_length=150)),
                ('questions_count', models.PositiveIntegerField(default=0)),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='medium', max_length=20)),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_bank', to='portal.trainerprofile')),
            ],
        ),
        migrations.CreateModel(
            name='PendingTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=150)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pending_tasks', to='portal.trainerprofile')),
            ],
        ),
        migrations.AddField(
            model_name='batch',
            name='trainer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='portal.trainerprofile'),
        ),
        migrations.CreateModel(
            name='TrainerStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('batch_name', models.CharField(max_length=150)),
                ('score_pct', models.DecimalField(decimal_places=1, default=0, max_digits=5)),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='portal.trainerprofile')),
            ],
            options={
                'ordering': ['-score_pct'],
            },
        ),
        migrations.CreateModel(
            name='TrainerTrendPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month_label', models.CharField(max_length=20)),
                ('order', models.PositiveIntegerField(default=0)),
                ('avg_percentage', models.DecimalField(decimal_places=1, default=0, max_digits=5)),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trend_points', to='portal.trainerprofile')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
