# Generated by Django 6.0.7 on 2026-09-28 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='partnercollege',
            options={'ordering': ['-students_count'], 'verbose_name': 'College finance summary', 'verbose_name_plural': 'College finance summaries'},
        ),
    ]
