# Generated by Django 6.0.7 on 2026-09-28 10:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
        ('portal', '0002_alter_partnercollege_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='OnlineTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160)),
                ('instructions', models.TextField(blank=True)),
                ('opens_at', models.DateTimeField()),
                ('closes_at', models.DateTimeField()),
                ('duration_minutes', models.PositiveIntegerField(default=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='online_tests', to='portal.trainerprofile')),
            ],
            options={
                'ordering': ['-opens_at'],
            },
        ),
        migrations.CreateModel(
            name='OnlineTestAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('in_progress', 'In progress'), ('submitted', 'Submitted')], default='in_progress', max_length=20)),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('possible_points', models.PositiveIntegerField(default=0)),
                ('pending_manual_review', models.PositiveIntegerField(default=0)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='online_test_attempts', to='dashboard.studentprofile')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='portal.onlinetest')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='OnlineTestQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt', models.TextField()),
                ('question_type', models.CharField(choices=[('single', 'Multiple choice'), ('multiple', 'Select all that apply'), ('true_false', 'True or false'), ('short', 'Short answer'), ('essay', 'Written response')], max_length=20)),
                ('options', models.JSONField(blank=True, default=list)),
                ('correct_answers', models.JSONField(blank=True, default=list)),
                ('points', models.PositiveIntegerField(default=1)),
                ('order', models.PositiveIntegerField(default=0)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='portal.onlinetest')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='OnlineTestAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response', models.JSONField(blank=True, default=list)),
                ('points_awarded', models.PositiveIntegerField(default=0)),
                ('reviewed', models.BooleanField(default=False)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='portal.onlinetestattempt')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='portal.onlinetestquestion')),
            ],
        ),
        migrations.AddConstraint(
            model_name='onlinetestattempt',
            constraint=models.UniqueConstraint(fields=('test', 'student'), name='unique_online_test_attempt'),
        ),
        migrations.AddConstraint(
            model_name='onlinetestanswer',
            constraint=models.UniqueConstraint(fields=('attempt', 'question'), name='unique_answer_per_test_question'),
        ),
    ]
