# Generated by Django 6.0.7 on 2026-09-28 10:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_onlinetest_onlinetestattempt_onlinetestquestion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='onlinetest',
            name='college',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='online_tests', to='portal.collegeprofile'),
        ),
        migrations.AddField(
            model_name='onlinetestanswer',
            name='uploaded_file',
            field=models.FileField(blank=True, null=True, upload_to='test_answers/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='onlinetestquestion',
            name='question_type',
            field=models.CharField(choices=[('single', 'Multiple choice'), ('multiple', 'Select all that apply'), ('true_false', 'True or false'), ('fill_blank', 'Fill in the blank'), ('matching', 'Matching / ordering'), ('numeric', 'Numeric'), ('short', 'Short answer'), ('essay', 'Written response'), ('file', 'File upload')], max_length=20),
        ),
    ]
