# Generated by Django 6.0.7 on 2026-10-01 04:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0004_onlinetest_college_onlinetestanswer_uploaded_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainerprofile',
            name='college',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trainers', to='portal.collegeprofile'),
        ),
    ]
