# Generated by Django 6.0.7 on 2026-10-01 05:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0005_trainerprofile_college'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainerAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('is_available', models.BooleanField(default=True)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability', to='portal.trainerprofile')),
            ],
            options={
                'ordering': ['date'],
                'unique_together': {('trainer', 'date')},
            },
        ),
    ]
