# Generated by Django 6.0.7 on 2026-10-01 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0006_traineravailability'),
    ]

    operations = [
        migrations.AddField(
            model_name='onlinetest',
            name='external_url',
            field=models.URLField(blank=True, default=''),
        ),
    ]
