# Generated by Django 5.2.17 on 2026-10-06 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0010_onlinetest_external_link_email_sent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminstudentrecord',
            name='department',
            field=models.CharField(max_length=150),
        ),
    ]
